import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { createHash } from 'node:crypto'

const BASE = '/Music-Practice/'

// Emits sw.js at build time with the exact list of built files, so the whole
// app shell (and library.json, which is bundled into the JS) is precached on
// install. No extra dependency; dev server is unaffected.
const songbookPwa = () => ({
  name: 'songbook-pwa',
  apply: 'build',
  generateBundle(_, bundle) {
    const built = Object.keys(bundle).filter((f) => f !== 'sw.js').map((f) => BASE + f)
    const shell = ['', 'index.html', 'manifest.webmanifest', 'apple-touch-icon.png', 'icon-192.png', 'icon-512.png'].map((f) => BASE + f)
    const precache = [...shell, ...built]
    const version = createHash('sha1').update(precache.join('\n')).digest('hex').slice(0, 10)
    const source = `// generated by vite.config.js (songbook-pwa) — do not edit
const CACHE = 'songbook-${version}';
const BASE = '${BASE}';
const PRECACHE = ${JSON.stringify(precache)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;
  const isFont = /fonts\\.(googleapis|gstatic)\\.com$/.test(url.hostname);
  // The set-list API is never cached here: the app keeps its own copy in localStorage.
  if (!sameOrigin && !isFont) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: sameOrigin }).then((hit) => hit || fetch(req).then((res) => {
      if (res && (res.ok || res.type === 'opaque')) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => (req.mode === 'navigate' ? caches.match(BASE + 'index.html') : Response.error())))
  );
});
`
    this.emitFile({ type: 'asset', fileName: 'sw.js', source })
  },
})

export default defineConfig({
  plugins: [react(), songbookPwa()],
  base: BASE,
})
